### ISSUE TITLE
F5 LTM 10.x and 11.x compatible?

### ISSUE THREAD

**Issue by J0TTaS** [f5devcentral/f5-eclipse-plugin#4]
Hello,

Before posting more issues about this plugin I would ask if it's possible running the plugin on v10.x or v11.x version? I have found several problems when connecting to my F5 LTM v10.x and v11.x appliances. As far as I could have tried through all my F5 appliances I got the next issues: java.lang.NullPointerException, GeneralEngineSSL Error (I posted an issue about this error a day ago), HTTP 404 error code exception and HTTP 401 error code exception:

![nullpointerexception](https://user-images.githubusercontent.com/7755448/39802270-f2de31f2-536d-11e8-9ef0-219e04d90022.PNG)

![generalsslexception](https://user-images.githubusercontent.com/7755448/39802286-f89b942c-536d-11e8-8033-587e321efc0f.PNG)

![httperrorcode_404](https://user-images.githubusercontent.com/7755448/39802295-fca1ab6a-536d-11e8-948a-14f78c83344c.PNG)

![httperrorcode_404](https://user-images.githubusercontent.com/7755448/39802311-01d8b83a-536e-11e8-8080-db223cb593c6.PNG)

Fortunately the plugin works well through all my F5 LTM v12.x appliances!!!

**Comment by rreichenbach** [comment]
I'm glad it's working well for your 12.x appliances.  Yes, as the README states (and as you've discovered), the plugin Only supports TMOS versions 12.1 and later.  For iAppLX and iControl LX support, you'll need 13.1 or later.  This is simply because the F5 Eclipse plugin leverages API's which only exist in those versions of TMOS.
